# Generated by Django 5.2 on 2025-04-28 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_location_options_location_residents_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='episode',
        ),
        migrations.AlterField(
            model_name='character',
            name='gender',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='character',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='character',
            name='location',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='character',
            name='origin',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='character',
            name='species',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='character',
            name='status',
            field=models.CharField(max_length=50),
        ),
        migrations.AddField(
            model_name='character',
            name='episode',
            field=models.JSONField(default=list),
        ),
    ]
